title: Diensten
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
          -
            handle: dienst_titel
            field:
              type: text
              display: 'Dienst titel'
          -
            handle: dienst_image
            field:
              container: assets
              type: assets
              display: 'Dienst image'
          -
            handle: dienst_text
            field:
              remove_empty_nodes: false
              type: bard
              display: 'Dienst text'
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
